# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03b158950455d9183ace3ec7a08368496ff8bc6cfe1373f3784107df5af9e9752df05feb3a99f10a43808032c3cdf9e9800a1a3a47ee96938bd488a6b468650f

test:
  secret_key_base: fe8c6c75ff81cd90827d508162b0fb24ac71b5b00b376754e584b9979303d40d8c2dba5c20b7a3c9b5f25d823712e8bf3d35492c82800e79d197bcf740e06cfd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
